In [2]:
import pandas as pd
pd.set_option('display.max_columns',None)
import numpy as np
import re


# excel 14개 카테고리별로 읽어오기
# - sat - before - qual - bro - naa - pack 
# - wrong - ss - delay - od - part - etc - ret

In [26]:
fname = '대통합_최종_190222.xlsx'

## sat : '만족' dictionary 생성

In [27]:
sat = pd.read_excel(fname, sheet_name = 'SAT', skiprows=[0])

In [28]:
stdict= []
for ind, i in sat.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            stdict.append(i[j].strip().lower())
            #print(i[j])
print(len(stdict))
stdict = list(set(stdict))

1020


In [29]:
len(stdict)

991

## qual : '제품불량' dictionary 생성

In [30]:
qual = pd.read_excel(fname, sheet_name = '제불', skiprows=[0])

In [31]:
qualdict= []
for ind, i in qual.iterrows():
    for j in range(len(i)):
        if pd.notnull(i[j]):
            qualdict.append(i[j].strip().lower())
print(len(qualdict))
qualdict = list(set(qualdict))

243


In [32]:
len(qualdict)

227

## bro : '제품훼손' dictionary 생성

In [33]:
bro = pd.read_excel(fname, sheet_name = '제훼', skiprows=[0])

In [34]:
brodict= []
for ind, i in bro.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            brodict.append(i[j].strip().lower())
print(len(brodict))
brodict = list(set(brodict))

88


In [35]:
len(brodict)

86

## pack : '배송부주의' dictionary 생성

In [36]:
pack = pd.read_excel(fname, sheet_name = 'PACKAGING', skiprows=[0])

In [37]:
packdict= []
for ind, i in pack.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            packdict.append(i[j].strip().lower())
print(len(packdict))
packdict = list(set(packdict))

79


In [38]:
len(packdict)

77

## before : 'before estimate' dictionary 생성

In [39]:
before = pd.read_excel(fname, sheet_name = 'B.E.', skiprows=[0,1,2])

In [40]:
beforedict= []
for ind, i in before.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            beforedict.append(i[j].strip().lower())
            
print(len(beforedict))
beforedict = list(set(beforedict))

419


In [41]:
len(beforedict)

406

## delay : 'delayed' dictionary 생성

In [42]:
delay = pd.read_excel(fname, sheet_name = 'DELAY', skiprows=[0,1])

In [43]:
delaydict= []
for ind, i in delay.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            delaydict.append(i[j].strip().lower())
            
print(len(delaydict))
delaydict = list(set(delaydict))

488


In [44]:
len(delaydict)


472

## part : '부분배송,누락' dictionary 생성

In [45]:
part = pd.read_excel(fname, sheet_name = '배누&부배', skiprows=[0])

In [46]:
partdict= []
for ind, i in part.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            partdict.append(i[j].strip().lower())
print(len(partdict))
partdict = list(set(partdict))

263


In [47]:
len(partdict)

233

## wrong : '잘못된배송' dictionary 생성

In [48]:
wrong = pd.read_excel(fname, sheet_name = 'WRONG PRODUCT', skiprows=[0])

In [49]:
wrong = wrong.iloc[:,6:]

In [50]:
wrongdict= []
for ind, i in wrong.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            wrongdict.append(i[j].strip().lower())
print(len(wrongdict))
wrongdict = list(set(wrongdict))

107


In [51]:
len(wrongdict)

100

## ret : 'return' dictionary 생성

In [52]:
ret = pd.read_excel(fname, sheet_name = 'return', skiprows=[0])

In [53]:
retdict= []
for ind, i in ret.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            retdict.append(i[j].strip().lower())
print(len(retdict))
retdict = list(set(retdict))

186


In [54]:
len(retdict)

175

## naa : 'not as announced' dictionary 생성

In [55]:
naa = pd.read_excel(fname, sheet_name = 'NAA', skiprows=[0])

In [56]:
naadict= []
for ind, i in naa.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            naadict.append(i[j].strip().lower())
print(len(naadict))
naadict = list(set(naadict))

114


In [57]:
len(naadict)

110

## ss: '서비스' dictionary 생성

In [58]:
ss = pd.read_excel(fname, sheet_name = 'S.S', skiprows=[0])

In [59]:
ssdict= []
for ind, i in ss.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            ssdict.append(i[j].strip().lower())
print(len(ssdict))
ssdict = list(set(ssdict))

224


In [60]:
len(ssdict)

212

## od : 'other delivery' dictionary 생성

In [61]:
od = pd.read_excel(fname, sheet_name = 'O.D', skiprows=[0,1])

In [62]:
oddict= []
for ind, i in od.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            oddict.append(i[j].strip().lower())
print(len(oddict))
oddict = list(set(oddict))

283


In [63]:
len(oddict)

279

## 'ETC' dictionary 생성

In [64]:
etc = pd.read_excel(fname, sheet_name = 'ETC', skiprows=[0,1])

In [65]:
etcdict= []
for ind, i in etc.iterrows():
    for j in range(len(i)):      
        if pd.notnull(i[j]):
            etcdict.append(i[j].strip().lower())
print(len(etcdict))
etcdict = list(set(etcdict))

148


In [66]:
len(etcdict)

144

# 전체 합치기

In [67]:
dictionary = {'sat':stdict,'qual':qualdict,'bro':brodict,'pack':packdict, 
             'before':beforedict, 'delay':delaydict,'part':partdict,
             'wrong':wrongdict, 'ret':retdict, 'naa':naadict,'ss':ssdict,
             'od':oddict,'etc':etcdict}

In [68]:
dict_df = pd.DataFrame({key:pd.Series(value) for key, value in dictionary.items()})

In [101]:
dict_df.head()

sat  \
0                                               okay   
1                                       liked to buy   
2  product corresponds with the very good adverti...   
3                                               love   
4                              recommend this seller   

                                 qual                        bro  \
0       only __graph__ work correctly          product was dirty   
1                did not come running               came kneaded   
2              was partially impaired              a bit crushed   
3  one of the controls is not working  came completely destroyed   
4        could have a slightly better       product came spoiled   

                                pack  \
0        came in a loose plastic bag   
1                  very badly packed   
2           spilled in the packaging   
3  did not like the shipping package   
4             product causing a loss   

                                      before  \
0                    still ahead of schedule   
1  the delivery was made before the deadline   
2                           fast on delivery   
3                   delivered in only 6 days   
4     delivery of the product was surprising   

                                delay                              part  \
0                have not arrived yet  did not receive all the products   
1        product takes almost 30 days                 had no spare part   
2                              so far  arrived just one of the products   
3            need to receive urgently          only gave me one product   
4  was not delivered without response       when the others will arrive   

                             wrong                             ret  \
0  delivered was not the purchased              asked for a return   
1        sent me the wrong product            store did not cancel   
2                      sent absurd        proceed to be reimbursed   
3    came wrong smaller and narrow                  need to change   
4                       came wrong  the order was delivered anyway   

                                                 naa  \
0                   differs (greatly) from the photo   
1                       sent me wrong in the picture   
2  product does not match (the size and weight) d...   
3  in the product description account that the sa...   
4                    the photo presented on the site   

                                              ss  \
0                         had problem with stock   
1                                  lack of stock   
2  lack of respect and honesty with the consumer   
3                          still did not contact   
4                           waiting for response   

                                           od  \
0                problem has been in delivery   
1  did not have updates of the product status   
2      to the post office to pick the product   
3                   had to go get the product   
4            freight by the size of the order   

                                   etc  
0  expected the __thing__ to be bigger  
1                 found size too small  
2                         will not use  
3    the product was not what i wanted  
4                    without liability

# 정규표현 딕셔너리

In [447]:
#dict_df = pd.read_excel('total_dict_apo_2402.xlsx')

## 종인오빠 정규표현 찾기

In [45]:
import re

result = []
g = re.compile(r'[__]')

for col_num in range(len(dict_df.columns)):
    col = dict_df.iloc[:,col_num].dropna().tolist()
    
    temp = []
    
    for i in col:
        
        m = g.search(i)
        if m:
            temp.append(i)
    print(len(temp))        
    result.append(temp)



0
11
3
1
10
23
4
0
0
0
0
0
4


In [46]:
result

[[],
 ['found the __product__ very badly finished',
  'the quality of the __product__ is very bad',
  'poor __product__ quality',
  'the __product__ is of poor quality',
  'the __product__ is awful',
  'did not like the matter of the __product__',
  'found the __product__ tilted',
  'the quality of the __product__ is not so good',
  'only __graph__ work correctly',
  'the __product__ is low',
  'not like the matter of the __product__'],
 ['the __part__ has already broken',
  'came with the __thing__ bent',
  'product came with the __something__ worn'],
 ['the box of the __product__ came with a small rip'],
 ['product arrived before__end__',
  'product delivered before the _dhea_ term',
  'satisfied with __a__ __b__ and delivery time',
  'arrive in only __num__ days',
  'arrived in __num__ days',
  'arrived __a__ __b__ and fast',
  'fast and __adj__ delivery',
  'fast and very __adj__ way',
  'delivered __num__ days befoe the expected deadline',
  'excellent __noun__ and delivery'],
 ['

In [47]:
new2 = []
for cols in range(len(result)):
    temp = []
    for i in result[cols]:
        
        splitedlist = i.split('__')
        
        new_items = ['(\s+\w+){0,7}\s+' if ind % 2 == 1 else x.strip() for ind,x in enumerate(splitedlist)]

    
        string = new_items[0]
        
        for j in range(1,len(new_items)):
            string = string + new_items[j]
        #print(string)
        
        temp.append(string)
    new2.append(temp)

In [48]:
new2[0]

[]

In [49]:
newdict_df = []
for i in range(len(dict_df.columns)):
    newcol = dict_df.iloc[:,i].dropna().tolist()
    for j in new2[i]:
        newcol.append(j)
    
    newdict_df.append(newcol)

In [50]:
final = pd.Series(newdict_df[0])
for i in range(1,len(newdict_df)):
    temp = pd.Series(newdict_df[i])
    final = pd.concat([final,temp],axis=1)

In [51]:
final.columns = dict_df.columns
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991 entries, 0 to 990
Data columns (total 13 columns):
sat       991 non-null object
qual      238 non-null object
bro       89 non-null object
pack      78 non-null object
before    416 non-null object
delay     495 non-null object
part      237 non-null object
wrong     100 non-null object
ret       175 non-null object
naa       110 non-null object
ss        212 non-null object
od        279 non-null object
etc       148 non-null object
dtypes: object(13)
memory usage: 100.7+ KB


## 내꺼 정규표현 찾기

In [52]:
import re

result = []
g = re.compile(r'[()]')

for col_num in range(len(dict_df.columns)):
    col = dict_df.iloc[:,col_num].dropna().tolist()
    
    temp = []
    
    for i in col:
        
        m = g.search(i)
        if m:
            a = i.replace("(", "__")
            b = a.replace(")","__")
            temp.append(b)
    print(len(temp))
    result.append(temp)

0
0
0
0
0
2
13
20
1
38
1
0
3


In [53]:
result

[[],
 [],
 [],
 [],
 [],
 ['has been almost __num__ month__s__ since i made the purchase',
  'bought __article__ __noun__ almost __num_ month__s__ ago'],
 ['came with no __yellow ink__',
  'bought __2 units__ and only __one__',
  'actually bought __two units__',
  'did not receive __the fixing screws__',
  'came without __the flannel__',
  'came missing __1__ piece',
  'was going to come __3 shpaes according to the photo__ but it came __1__',
  'bought __2__ and only delivered __1__',
  'only __the cover__ arrived',
  '__the charger__ without __the cable part__',
  'missed __the brackets__',
  'missed __the leaf pendant watch__',
  'paid for __24 wharfers__ and came'],
 ['bought __the book 6 edition__ and received __the 5 edition__',
  'made a request for __a kit 12 brushes brush makeup case cup pink__ i was sent __the black__',
  'asked for __a necklace__ and came',
  'was asked __the number 37 and came 39 40 so__ came wrong __numbering__',
  'made two requests for __a hose to the wat

In [54]:
new2 = []
for cols in range(len(result)):
    temp = []
    for i in result[cols]:
        
        splitedlist = i.split('__')
        
        new_items = ['(\s+\w+){0,7}\s+' if ind % 2 == 1 else x.strip() for ind,x in enumerate(splitedlist)]

    
        string = new_items[0]
        
        for j in range(1,len(new_items)):
            string = string + new_items[j]
        #print(string)
        
        temp.append(string)
    new2.append(temp)

In [55]:
new2

[[],
 [],
 [],
 [],
 [],
 ['has been almost(\\s+\\w+){0,7}\\s+month(\\s+\\w+){0,7}\\s+since i made the purchase',
  'bought(\\s+\\w+){0,7}\\s+(\\s+\\w+){0,7}\\s+almost(\\s+\\w+){0,7}\\s+s(\\s+\\w+){0,7}\\s+'],
 ['came with no(\\s+\\w+){0,7}\\s+',
  'bought(\\s+\\w+){0,7}\\s+and only(\\s+\\w+){0,7}\\s+',
  'actually bought(\\s+\\w+){0,7}\\s+',
  'did not receive(\\s+\\w+){0,7}\\s+',
  'came without(\\s+\\w+){0,7}\\s+',
  'came missing(\\s+\\w+){0,7}\\s+piece',
  'was going to come(\\s+\\w+){0,7}\\s+but it came(\\s+\\w+){0,7}\\s+',
  'bought(\\s+\\w+){0,7}\\s+and only delivered(\\s+\\w+){0,7}\\s+',
  'only(\\s+\\w+){0,7}\\s+arrived',
  '(\\s+\\w+){0,7}\\s+without(\\s+\\w+){0,7}\\s+',
  'missed(\\s+\\w+){0,7}\\s+',
  'missed(\\s+\\w+){0,7}\\s+',
  'paid for(\\s+\\w+){0,7}\\s+and came'],
 ['bought(\\s+\\w+){0,7}\\s+and received(\\s+\\w+){0,7}\\s+',
  'made a request for(\\s+\\w+){0,7}\\s+i was sent(\\s+\\w+){0,7}\\s+',
  'asked for(\\s+\\w+){0,7}\\s+and came',
  'was asked(\\s+\\w+){0,7}\\

In [56]:
dict_df = final
newdict_df = []
for i in range(len(dict_df.columns)):
    newcol = dict_df.iloc[:,i].dropna().tolist()
    for j in new2[i]:
        newcol.append(j)
    
    newdict_df.append(newcol)
    
final = pd.Series(newdict_df[0])
for i in range(1,len(newdict_df)):
    temp = pd.Series(newdict_df[i])
    final = pd.concat([final,temp],axis=1)

In [57]:
final.columns = dict_df.columns

In [58]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991 entries, 0 to 990
Data columns (total 13 columns):
sat       991 non-null object
qual      238 non-null object
bro       89 non-null object
pack      78 non-null object
before    416 non-null object
delay     497 non-null object
part      250 non-null object
wrong     120 non-null object
ret       176 non-null object
naa       148 non-null object
ss        213 non-null object
od        279 non-null object
etc       151 non-null object
dtypes: object(13)
memory usage: 100.7+ KB


In [65]:
## 중복제거
for i in range(len(final.columns)):
    temp = final.iloc[:,i].dropna().tolist()
    print(len(temp), len(set(temp)))
    if i ==0:
        final2 = pd.Series(list(set(temp)))
    else:
        final2 = pd.concat([final2,pd.Series(list(set(temp)))],axis=1)
final2.columns = final.columns
## 현재 전체 데이터셋 이름 final2

991 991
238 238
89 89
78 78
416 415
497 497
250 249
120 120
176 176
148 148
213 213
279 279
151 151


In [66]:
final2.head()

sat                                   qual  \
0           packaged well                was buying the original   
1  you are very efficient                      did not even open   
2          good precision                      of lower material   
3         it°øs all right  thought it would be of better quality   
4       is very beautiful         bought the product as original   

                             bro  \
0    coming with a slight defect   
1        delivered broken opened   
2      came completely destroyed   
3                      came torn   
4  the handle has already broken   

                                                pack  \
0                              came with a small rip   
1                           one of the cans was open   
2                                   straps are loose   
3  product could well come wrapped up not to draw...   
4                    arrived in a doubtful packaging   

                                           before  \
0                                   arrived right   
1            satisfied with the services provided   
2  delivered 10 days before the expected deadline   
3               delivered before the correct time   
4                   product arrived before__end__   

                          delay                             part  \
0               nothing arrived               received one while   
1             an absurd waiting        came with no (yellow ink)   
2              i want the watch       did not receive everything   
3            after the deadline              one of the products   
4  have not received my product  received only 1 of the products   

                                               wrong  \
0                                   another one came   
1          received the product with the wrong color   
2  bought (the book 6 edition) and received (the ...   
3                                    delivered wrong   
4               announced one thing and sent another   

                                                 ret  \
0                      will be returning the product   
1                           make a possible exchange   
2  canceling the purchase did not fulfill the val...   
3  asked for the cancellation but system did not ...   
4                           had canceled the product   

                                                 naa  \
0  product does not match (the size and weight) d...   
1          wanting (the cover) the same as the photo   
2  the photo showed (the head with the fully iy b...   
3              differs(\s+\w+){0,7}\s+from the photo   
4  not even the product of the photo anymore from...   

                                              ss  \
0                          still got no response   
1                        can't solve the problem   
2                           had to complain back   
3                        waiting for the contact   
4  after payment did not have available in stock   

                                                  od  \
0                                        in the mail   
1             do not know where the product got lost   
2                    app says my scent was delivered   
3  delivery deadline was before christmas suddenl...   
4                 freight policy does not make sense   

                                                 etc  
0                                   did not fix well  
1  did not fulfill the value of the offer that it...  
2                                    a bit small for  
3                        only had problems this time  
4                              was not as i expected

In [73]:
final.to_excel('정규표현마지막_2402.xlsx')

# 각 딕셔너리 사이에 중복된 표현 있는지 파악

In [69]:
#dict_df = pd.read_excel('total_dict_temp1_2202.xlsx')
dict_df = final2

NameError: name 'final2' is not defined

In [7]:
dict_df.head()

sat  \
0                                               okay   
1                                       liked to buy   
2  product corresponds with the very good adverti...   
3                                               love   
4                              recommend this seller   

                                 qual                        bro  \
0       only __graph__ work correctly          product was dirty   
1                did not come running               came kneaded   
2              was partially impaired              a bit crushed   
3  one of the controls is not working  came completely destroyed   
4        could have a slightly better       product came spoiled   

                                pack  \
0        came in a loose plastic bag   
1                  very badly packed   
2           spilled in the packaging   
3  did not like the shipping package   
4             product causing a loss   

                                      before  \
0                    still ahead of schedule   
1  the delivery was made before the deadline   
2                           fast on delivery   
3                   delivered in only 6 days   
4     delivery of the product was surprising   

                                delay                              part  \
0                have not arrived yet  did not receive all the products   
1        product takes almost 30 days                 had no spare part   
2                              so far  arrived just one of the products   
3            need to receive urgently          only gave me one product   
4  was not delivered without response       when the others will arrive   

                             wrong                             ret  \
0  delivered was not the purchased              asked for a return   
1        sent me the wrong product            store did not cancel   
2                      sent absurd        proceed to be reimbursed   
3    came wrong smaller and narrow                  need to change   
4                       came wrong  the order was delivered anyway   

                                                 naa  \
0                   differs (greatly) from the photo   
1                       sent me wrong in the picture   
2  product does not match (the size and weight) d...   
3  in the product description account that the sa...   
4                    the photo presented on the site   

                                              ss  \
0                         had problem with stock   
1                                  lack of stock   
2  lack of respect and honesty with the consumer   
3                          still did not contact   
4                           waiting for response   

                                           od  \
0                problem has been in delivery   
1  did not have updates of the product status   
2      to the post office to pick the product   
3                   had to go get the product   
4            freight by the size of the order   

                                   etc  
0  expected the __thing__ to be bigger  
1                 found size too small  
2                         will not use  
3    the product was not what i wanted  
4                    without liability

In [70]:
col = dict_df.columns

In [71]:
duplicated = []
for i in range(len(dict_df.columns)):
    check = dict_df.iloc[:,i]
    rest = dict_df.iloc[:,dict_df.columns != col[i]]

    for element in check:
        for ind,j in rest.iteritems():
            if (element in list(j)) & (pd.notnull(element)):
                duplicated.append(element)

In [72]:
duplicated=list(set(duplicated))

In [73]:
len(duplicated)

0

In [72]:
vals = []
for i in duplicated:
    temp = []
    for ind,j in dict_df.iteritems():
        if i in list(j):
            temp.append(ind)
    vals.append(temp)

In [397]:
newdf = []
for i in range(len(duplicated)):
    new = []
    new.append(duplicated[i])
    for j in range(len(vals[i])):
        new.append(vals[i][j])
    newdf.append(new)

In [398]:
newdf2 = pd.DataFrame(newdf, columns = ['dict','ctg1','ctg2'])

In [399]:
newdf2

dict  ctg1   ctg2
0  came duplicated  part  wrong

In [117]:
newdf2.to_excel('중복된표현들.xlsx')

In [19]:
dict_df = pd.read_excel('total_dict_temp1_2202.xlsx')

In [56]:
dict_df.head(20)

sat  \
0                                                okay   
1                                        liked to buy   
2   product corresponds with the very good adverti...   
3                                                love   
4                               recommend this seller   
5                                     trust this site   
6                        quality product as announced   
7       hope that you continue to have many customers   
8                                       great to keep   
9                                     very good price   
10                                          beautiful   
11                               delivery well packed   
12                               satisfactory product   
13                          received the product well   
14                              pleased with purchase   
15                                   love shopping on   
16                                     store is great   
17                                      it's reliable   
18                                  easy illumination   
19                           satisfied with the store   

                                       qual  \
0             only __graph__ work correctly   
1                      did not come running   
2                    was partially impaired   
3        one of the controls is not working   
4              could have a slightly better   
5                      very poorly produced   
6                        refilled cartridge   
7                inferior to what i thought   
8                       not worth the price   
9                             only two work   
10                        came an imitation   
11  distrust the originality of the product   
12                             weak product   
13                         quality inferior   
14           product that is of low quality   
15                 horrible without quality   
16                       is of poor quality   
17    did not like the matter of the cotins   
18       the __product__ is of poor quality   
19               does not have much quality   

                                         bro  \
0                          product was dirty   
1                               came kneaded   
2                              a bit crushed   
3                  came completely destroyed   
4                       product came spoiled   
5                                with defect   
6                           came with broken   
7                          came with cracked   
8                         came out defective   
9                                all damaged   
10                         have been kneaded   
11  product came with the __something__ worn   
12                 came with cracked failure   
13                    received product qebra   
14                                      flaw   
15                                 scratches   
16                              came spoiled   
17                   cover came with a crack   
18              my brushes have been kneaded   
19                         defective product   

                                                 pack  \
0                         came in a loose plastic bag   
1                                   very badly packed   
2                            spilled in the packaging   
3                   did not like the shipping package   
4                              product causing a loss   
5                           slightly better packaging   
6                             should be better packed   
7                               came with a small rip   
8           the box of the game came with a small rip   
9                            all the straps are loose   
10                            packed in a brown paper   
11  packaging came out a little open and the produ...   
12                                 doubtful packaging   
13                        wrapped only in a black bag   


### - '&#39;' 전처리

In [46]:
kk = 'i°øm happy' 

g= re.compile(r"(%s)"%'°ø')
m= g.search(kk)

In [47]:
if m:
    kk = kk.replace('°ø', "\'")
    
    print('yes',kk)
else:
    print('no',kk)

yes i'm happy


In [74]:
dict_df2 = dict_df
for ind,i in enumerate(range(13)):
    ori_col = dict_df.iloc[:,i]
    col = dict_df.iloc[:,i].dropna().tolist()
    new_col = []
    for ind2,j in enumerate(col):
        g = re.compile(r"(%s)"%'°ø')
        m = g.search(j)
        if m:
            print('@@')
            ori_col[ind2] = col[ind2].replace('°ø', "\'")
        
    
    dict_df2.iloc[:,ind] = ori_col
        
    

@@
@@
@@
@@
@@
@@
@@
@@
@@


In [75]:
#dict_df2.to_excel('total_dict_apo_2402.xlsx')
#dict_df2.to_excel('정규표현마지막_2402.xlsx')
dict_df2.to_excel('정규표현없이_마지막_2402.xlsx')

---
# --------------------------------------
# dict 테스트해보기

In [6]:
import pandas as pd
pd.set_option('display.max_columns',None)
import numpy as np
import re

In [2]:
#dict_df = pd.read_excel('정규표현마지막_2402.xlsx')
import pandas as pd
dict_df = pd.read_excel('정규표현없이_마지막_2402.xlsx')


In [7]:
df = pd.read_csv('classified_translated_3.csv')
#df = pd.read_excel('정답지(최종).xlsx')

### - classified '&#39;' 전처리

In [8]:
df = pd.read_excel('정답지(최종).xlsx')
comments = df['review_comment_message'].tolist()
new = []
for i in comments:
    
    if pd.notnull(i):
        apo = "&#39;"
        g = re.compile(r"(%s)"% apo)
        m = g.search(i)
        if m:
            new.append(i.replace('&#39;', "\'"))
        else:
            new.append(i)
    else: 
        new.append('')
        
df['review_comment_message'] = new


In [6]:
#df.to_csv('classified_translated_3_apo.csv', index_label= False, index=False)

### - satisfied 딕셔너리 전처리

In [9]:
new_sat = []
for i in dict_df['sat']:
    new_sat.append('[^(not)] '+i)
    
new_sat2 = []
for i in dict_df['sat']:
    new_sat2.append('^'+i)

In [80]:
new_sat[:5]

['[^(not)] came right on my product',
 '[^(not)] product is in accordance',
 '[^(not)] all right the request',
 '[^(not)] pleased',
 '[^(not)] very attentive']

In [10]:
votes=[]
for columns in range(len(dict_df.columns)):
    votes.append([0 for i in range(len(df['review_comment_message']))])

In [11]:
dictionary=[]
for columns in range(len(dict_df.columns)):
    dictionary.append(['' for i in range(len(df['review_comment_message']))])

In [278]:
'''
cnt =0
for ind,col in dict_df.iteritems():
    print(ind)
    for term in col.dropna():
        g = re.compile(r"(\b%s\b)"%term)
        for row,test in enumerate(df['review_comment_message']):
            
            m = g.search(str(test).lower())
            if m:
                votes[cnt][row] += 1
                if len(dictionary[cnt][row]) <= 1:
                    dictionary[cnt][row] += term
                else:
                    dictionary[cnt][row] += ',' + term
            
    cnt += 1
    print(cnt)
'''

'\ncnt =0\nfor ind,col in dict_df.iteritems():\n    print(ind)\n    for term in col.dropna():\n        g = re.compile(r"(\x08%s\x08)"%term)\n        for row,test in enumerate(df[\'review_comment_message\']):\n            \n            m = g.search(str(test).lower())\n            if m:\n                votes[cnt][row] += 1\n                if len(dictionary[cnt][row]) <= 1:\n                    dictionary[cnt][row] += term\n                else:\n                    dictionary[cnt][row] += \',\' + term\n            \n    cnt += 1\n    print(cnt)\n'

In [272]:
dict_df.columns

Index(['sat', 'qual', 'bro', 'pack', 'before', 'delay', 'part', 'wrong', 'ret',
       'naa', 'ss', 'od', 'etc'],
      dtype='object')

In [12]:
cnt =0
for ind,col in dict_df.iteritems():
    if ind == 'sat':
        col = new_sat
        note = 1
    else:
        col = col.dropna().tolist()
        note = 0
        
    for ind2, term in enumerate(col):
        g = re.compile(r"(\b%s\b)"%term)
        gg = re.compile(r"(%s\b)"%new_sat2[ind2])
        if note == 1:
            for row,test in enumerate(df['review_comment_message']):
                m = g.search(str(test).lower())
                mm = gg.search(str(test).lower())
                
                if m or mm:
                    votes[cnt][row] += 1

                    if len(dictionary[cnt][row]) <= 1:
                        dictionary[cnt][row] += term
                    else:
                        dictionary[cnt][row] += ',' + term
        elif note == 0:

            for row,test in enumerate(df['review_comment_message']):
                m = g.search(str(test).lower())
                if m:
                    votes[cnt][row] += 1
                    if len(dictionary[cnt][row]) <= 1:
                        dictionary[cnt][row] += term
                    else:
                        dictionary[cnt][row] += ',' + term
    cnt += 1
    print(cnt)

1
2
3
4
5
6
7
8
9
10
11
12
13


In [13]:
for columns in range(len(dict_df.columns)):
    df['votes_%s'%dict_df.columns[columns]] = votes[columns]  
    df['votes_%s_dictionary'%dict_df.columns[columns]] = dictionary[columns] 

In [85]:
#df.to_excel('class딕셔너리결과_2402.xlsx')
df.to_excel('class정규표현없이딕셔너리결과_2402.xlsx')

# --------------------------------------------------
## 정답지랑 비교 위해 binary_df 생성

In [14]:

#df = pd.read_excel('class딕셔너리결과_2402.xlsx')
df = pd.read_excel('class정규표현없이딕셔너리결과_2402.xlsx')
fig_df = df[['id','votes_sat','votes_qual','votes_bro','votes_pack','votes_before','votes_delay','votes_part','votes_wrong','votes_ret','votes_naa','votes_ss','votes_od','votes_etc']]

In [88]:
len(fig_df)

3584

In [68]:
df.head()

id order_status  order_products_value  order_freight_value  \
0   1    delivered                 89.99                14.38   
1   2    delivered                 69.00                15.23   
2   3    delivered                 99.80                15.86   
3   4    delivered                 87.00                12.74   
4   5    delivered                 99.90                17.95   

   order_items_qty  order_sellers_qty order_purchase_timestamp  \
0                1                  1                 00:41:01   
1                1                  1                 00:13:36   
2                2                  4                 00:50:42   
3                1                  1                 00:16:42   
4                1                  2                 00:58:42   

  order_aproved_at order_estimated_delivery_date  \
0         00:55:09                      00:00:00   
1  00:28:10.900000                      00:00:00   
2  00:29:56.400000                      00:00:00   
3         00:31:51                      00:00:00   
4  00:36:49.600000                      00:00:00   

  order_delivered_customer_date        customer_city customer_state  \
0               00:35:27.300000       Belo Horizonte             MG   
1                      00:13:05      Pocos de Caldas             MG   
2               00:51:31.100000  Sao Jose dos Campos             SP   
3               00:38:06.600000       Ribeirao Preto             SP   
4                      00:33:19       RIO DE JANEIRO             RJ   

   customer_zip_code_prefix   product_category_name  product_name_lenght  \
0                       308            beleza_saude                   59   
1                       377              brinquedos                   50   
2                       122      ferramentas_jardim                   59   
3                       140  informatica_acessorios                   45   
4                       205         cama_mesa_banho                   60   

   product_description_lenght  product_photos_qty  review_score  \
0                         492                   3             5   
1                         679                   4             5   
2                         341                   2             1   
3                         411                   1             4   
4                         189                   1             3   

   review_comment_title                             review_comment_message  \
0                   NaN                                          all right   
1                   NaN  the product arrived before the deadline congra...   
2                   NaN  was purchased 6 items from this store where up...   
3                   NaN       I found the delivery a little time consuming   
4                   NaN  I bought 02 sets of satin sheets and a quilt b...   

   satisfied  제품불량  제품훼손  패키징  not as announced  before estimate  delayed  \
0        1.0   NaN   NaN  NaN               NaN              NaN      NaN   
1        1.0   NaN   NaN  NaN               NaN              1.0      NaN   
2        NaN   NaN   NaN  NaN               NaN              NaN      1.0   
3        NaN   NaN   NaN  NaN               NaN              NaN      1.0   
4        NaN   NaN   NaN  NaN               NaN              NaN      NaN   

   배송누락 및 부분배송  잘못된 배송  other delivery  seller service  other complaints  \
0          NaN     NaN             NaN             NaN               NaN   
1          NaN     NaN             NaN             NaN               NaN   
2          NaN     NaN             NaN             NaN               NaN   
3          NaN     NaN             NaN             NaN               NaN   
4          1.0     NaN             NaN             NaN               NaN   

   return review_creation_date    review_answer_timestamp  \
0     NaN             00:00:00  2017-09-10 03:27:54+00:00   
1     NaN             00:00:00  2017-10-03 05:34:20+00:00   
2     NaN             00:00:00  2018-02-02 

In [72]:
##종인오빠 보내기용 binary df col 붙이기
binary_df = df
colnames = ['votes_sat','votes_qual','votes_bro','votes_pack','votes_before','votes_delay','votes_part','votes_wrong','votes_ret','votes_naa','votes_ss','votes_od','votes_etc']
#for colname in colnames:

#    col = binary_df[colname].tolist()
#    col2 = [1 if val>=1 else 0 for val in col]
#    binary_df[colname] = col2
    

In [80]:
#binary_df.to_csv('data_classified.csv', index=False, index_label=False)

In [78]:
len(binary_df)
#####################################

2786

In [87]:
binary_df = fig_df

for i in range(1,len(fig_df.columns)):
    col = fig_df.iloc[:,i].tolist()
    col2 = [1 if val>=1 else 0 for val in col]
    binary_df.iloc[:,i] = col2

/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:630: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [248]:
binary_df.head()

id  votes_sat  votes_qual  votes_bro  votes_pack  votes_before  \
0   1          1           0          0           0             0   
1   2          1           0          0           0             1   
2   3          0           0          0           0             1   
3   4          0           0          0           0             1   
4   5          0           0          0           0             0   

   votes_delay  votes_part  votes_wrong  votes_ret  votes_naa  votes_ss  \
0            0           0            0          0          0         0   
1            0           0            0          0          0         0   
2            1           0            0          0          0         0   
3            1           0            0          0          0         0   
4            1           1            0          0          0         0   

   votes_od  votes_etc  
0         0          0  
1         0          0  
2         0          0  
3         0          0  
4         0          0

### - 정답지 읽어오기

In [16]:
answer = pd.read_excel('정답지(최종).xlsx')

In [82]:
answer.columns

Index(['id', 'order_status', 'order_products_value', 'order_freight_value',
       'order_items_qty', 'order_sellers_qty', 'order_purchase_timestamp',
       'order_aproved_at', 'order_estimated_delivery_date',
       'order_delivered_customer_date', 'customer_city', 'customer_state',
       'customer_zip_code_prefix', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'review_score', 'review_comment_title',
       'review_comment_message', 'satisfied', '제품불량', '제품훼손', '패키징',
       'not as announced', 'before estimate', 'delayed', '배송누락 및 부분배송',
       '잘못된 배송', 'other delivery', 'seller service', 'other complaints',
       'return', 'review_creation_date', 'review_answer_timestamp',
       'votes_before_estimate', 'votes_delayed', 'votes_low_quality',
       'votes_return', 'votes_not_as_anounced', 'votes_partial_delivery',
       'votes_other_delivery', 'votes_other_order', 'votes_satisfied',
       'most_voted_subclass'

In [88]:
cols = [0]
[cols.append(i) for i in range(-26,-13)]

[None, None, None, None, None, None, None, None, None, None, None, None, None]

In [89]:
answer2 = answer.iloc[:,cols]
answer2.columns = ['id','votes_sat_as','votes_qual_as','votes_bro_as','votes_pack_as','votes_naa_as','votes_before_as','votes_delay_as','votes_part_as','votes_wrong_as','votes_od_as','votes_ss_as','votes_etc_as','votes_ret_as']

In [90]:
answer2.fillna(0, inplace=True)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


In [94]:
answer2.info()

id                 4719961.0
votes_sat_as          1232.0
votes_qual_as          127.0
votes_bro_as            49.0
votes_pack_as           28.0
votes_naa_as            59.0
votes_before_as        822.0
votes_delay_as         411.0
votes_part_as          273.0
votes_wrong_as          96.0
votes_od_as            137.0
votes_ss_as            160.0
votes_etc_as           211.0
votes_ret_as           127.0
dtype: float64

In [439]:
binary_df.sum()

id              6424320
votes_sat          1371
votes_qual          173
votes_bro            83
votes_pack           39
votes_before       1399
votes_delay         805
votes_part          583
votes_wrong          84
votes_ret           202
votes_naa            84
votes_ss            150
votes_od            193
votes_etc           177
dtype: int64

In [121]:
binary_df.sum()

id              6424320
votes_sat          2157
votes_qual          172
votes_bro            83
votes_pack           39
votes_before       1397
votes_delay         789
votes_part          397
votes_wrong          84
votes_ret           202
votes_naa            82
votes_ss            150
votes_od            193
votes_etc           177
dtype: int64

In [191]:
binary_df.sum()
## 정규표현식 이후 delay, part에서 크게 많아짐

id              6424320
votes_sat          2159
votes_qual          173
votes_bro            83
votes_pack           39
votes_before       1399
votes_delay         805
votes_part          583
votes_wrong          84
votes_ret           202
votes_naa            84
votes_ss            150
votes_od            193
votes_etc           177
dtype: int64

In [20]:
binary_df.sum()
## 정규표현식 & sat 이후

id              6424320
votes_sat          1375
votes_qual          173
votes_bro            83
votes_pack           39
votes_before       1399
votes_delay         805
votes_part          583
votes_wrong         150
votes_ret           202
votes_naa            84
votes_ss            150
votes_od            193
votes_etc           177
dtype: int64

In [91]:
binary_df.sum()
## 정규표현식 없이 sat만

id              6424320
votes_sat          1375
votes_qual          172
votes_bro            83
votes_pack           39
votes_before       1397
votes_delay         789
votes_part          397
votes_wrong         108
votes_ret           202
votes_naa            82
votes_ss            150
votes_od            193
votes_etc           177
dtype: int64

In [94]:
newdf = answer2.merge(binary_df, on= 'id', how='left') 

In [123]:
newdf.head()

id  votes_sat_as  votes_qual_as  votes_bro_as  votes_pack_as  votes_naa_as  \
0   1           1.0            0.0           0.0            0.0           0.0   
1   2           1.0            0.0           0.0            0.0           0.0   
2   3           0.0            0.0           0.0            0.0           0.0   
3   4           0.0            0.0           0.0            0.0           0.0   
4   5           0.0            0.0           0.0            0.0           0.0   

   votes_before_as  votes_delay_as  votes_part_as  votes_wrong_as  \
0              0.0             0.0            0.0             0.0   
1              1.0             0.0            0.0             0.0   
2              0.0             1.0            0.0             0.0   
3              0.0             1.0            0.0             0.0   
4              0.0             0.0            1.0             0.0   

   votes_od_as  votes_ss_as  votes_etc_as  votes_ret_as  votes_sat  \
0          0.0          0.0           0.0           0.0          1   
1          0.0          0.0           0.0           0.0          1   
2          0.0          0.0           0.0           0.0          0   
3          0.0          0.0           0.0           0.0          0   
4          0.0          0.0           0.0           0.0          0   

   votes_qual  votes_bro  votes_pack  votes_before  votes_delay  votes_part  \
0           0          0           0             0            0           0   
1           0          0           0             1            0           0   
2           0          0           0             1            1           0   
3           0          0           0             1            1           0   
4           0          0           0             0            1           1   

   votes_wrong  votes_ret  votes_naa  votes_ss  votes_od  votes_etc  
0            0          0          0         0         0          0  
1            0          0          0         0         0          0  
2            0          0          0         0         0          0  
3            0          0          0         0         0          0  
4            0          0          0         0         0          0

In [95]:
col_names = ['votes_sat','votes_qual','votes_bro','votes_pack','votes_naa','votes_before','votes_delay','votes_part','votes_wrong','votes_od','votes_ss','votes_etc','votes_ret']

confusion = []

for col_name in col_names:
    
    yy = 0
    yn = 0
    ny = 0
    nn = 0
    
    bin_col = newdf[col_name].tolist()
    ans_col = newdf[col_name+'_as'].tolist()
    
    for i in range(len(newdf)):
        
        
        if ans_col[i] == 1:
            if bin_col[i] == 1:
                yy += 1
                
            else:
                yn += 1
        else:
            if bin_col[i] == 1:
                ny += 1
            else:
                nn += 1
    print(yy, yn, ny, nn)
    print(yy + yn)
    confusion.append(np.matrix([[yy, ny], [yn, nn]]))
    

812 420 153 1401
1232
98 29 59 2600
127
45 4 27 2710
49
24 4 13 2745
28
42 17 31 2696
59
783 39 403 1561
822
384 27 251 2124
411
206 67 52 2461
273
63 33 29 2661
96
96 41 64 2585
137
84 76 51 2575
160
66 145 94 2481
211
119 8 50 2609
127


In [96]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
import sys
import matplotlib.pyplot as plt
col_names = ['votes_sat','votes_qual','votes_bro','votes_pack','votes_naa','votes_before','votes_delay','votes_part','votes_wrong','votes_od','votes_ss','votes_etc','votes_ret']
kor_col_names = ['만족','제품불량','제품훼손','포장문제','과대광고','빨리도착','배송지연','부분배송&누락','잘못배송','기타배송','서비스','기타','Return']
confusion = []

for ind,col_name in enumerate(col_names):

    predicted = newdf[col_name].tolist()
    actual = newdf[col_name+'_as'].tolist()
    
    results = confusion_matrix(actual, predicted) 
    print('%s Confusion Matrix :'%kor_col_names[ind])
    print(results) 
    print('%s Accuracy Score :'%kor_col_names[ind],accuracy_score(actual, predicted))
    print('%s Report : '%kor_col_names[ind])
    print(classification_report(actual, predicted))

만족 Confusion Matrix :
[[1401  153]
 [ 420  812]]
만족 Accuracy Score : 0.7943287867910983
만족 Report : 
              precision    recall  f1-score   support

         0.0       0.77      0.90      0.83      1554
         1.0       0.84      0.66      0.74      1232

   micro avg       0.79      0.79      0.79      2786
   macro avg       0.81      0.78      0.78      2786
weighted avg       0.80      0.79      0.79      2786

제품불량 Confusion Matrix :
[[2600   59]
 [  29   98]]
제품불량 Accuracy Score : 0.968413496051687
제품불량 Report : 
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98      2659
         1.0       0.62      0.77      0.69       127

   micro avg       0.97      0.97      0.97      2786
   macro avg       0.81      0.87      0.84      2786
weighted avg       0.97      0.97      0.97      2786

제품훼손 Confusion Matrix :
[[2710   27]
 [   4   45]]
제품훼손 Accuracy Score : 0.988872936109117
제품훼손 Report : 
              precision    recall

In [98]:
classification_report(actual, predicted)

str

In [417]:
confusion[0]

matrix([[ 808,  153],
        [ 424, 1401]])

In [210]:
confusion[1]

matrix([[  98,   60],
        [  29, 2599]])

In [211]:
condict = {x:y for x,y in zip(col_names,confusion)}

In [212]:
condict['votes_sat']

matrix([[1169,  483],
        [  63, 1071]])

In [213]:
1168/(1168+482)

0.7078787878787879

In [332]:
for i in range(13):
    print(col_names[i])
    print(confusion[i])

votes_sat
[[ 808  153]
 [ 424 1401]]
votes_qual
[[  98   60]
 [  29 2599]]
votes_bro
[[  45   27]
 [   4 2710]]
votes_pack
[[  24   13]
 [   4 2745]]
votes_naa
[[  43   32]
 [  16 2695]]
votes_before
[[ 785  403]
 [  37 1561]]
votes_delay
[[ 384  265]
 [  27 2110]]
votes_part
[[ 217  197]
 [  56 2316]]
votes_wrong
[[  49   21]
 [  47 2669]]
votes_od
[[  96   64]
 [  41 2585]]
votes_ss
[[  84   51]
 [  75 2576]]
votes_etc
[[  66   94]
 [ 145 2481]]
votes_ret
[[ 119   50]
 [   8 2609]]


In [418]:
sens =[]
for i in range(13):
    tp = confusion[i][0,0]
    fn = confusion[i][1,0]
    sen = tp/(tp+fn)
    sens.append(sen)
    

In [223]:
for i in range(13):
    print(col_names[i])
    print(round(sens[i],2))

votes_sat
0.95
votes_qual
0.77
votes_bro
0.92
votes_pack
0.86
votes_naa
0.73
votes_before
0.95
votes_delay
0.93
votes_part
0.79
votes_wrong
0.51
votes_od
0.7
votes_ss
0.53
votes_etc
0.31
votes_ret
0.94


In [419]:
## 민감도
for i in range(13):
    print(col_names[i])
    print(round(sens[i],2))

votes_sat
0.66
votes_qual
0.77
votes_bro
0.92
votes_pack
0.86
votes_naa
0.73
votes_before
0.95
votes_delay
0.93
votes_part
0.79
votes_wrong
0.51
votes_od
0.7
votes_ss
0.53
votes_etc
0.31
votes_ret
0.94


In [421]:
## 정확도
sens =[]
for i in range(13):
    tp = confusion[i][0,0]
    aa = confusion[i][0,1]
    fn = confusion[i][1,0]
    bb = confusion[i][1,1]
    sen = (tp+bb)/(tp+fn+aa+bb)
    sens.append(sen)
for i in range(13):
    print(col_names[i])
    print(round(sens[i],2))

votes_sat
0.79
votes_qual
0.97
votes_bro
0.99
votes_pack
0.99
votes_naa
0.98
votes_before
0.84
votes_delay
0.9
votes_part
0.91
votes_wrong
0.98
votes_od
0.96
votes_ss
0.95
votes_etc
0.91
votes_ret
0.98


In [422]:
## 특이도

sens =[]
for i in range(13):
    tp = confusion[i][0,0]
    aa = confusion[i][0,1]
    fn = confusion[i][1,0]
    bb = confusion[i][1,1]
    sen = bb/(aa+bb)
    sens.append(sen)
for i in range(13):
    print(col_names[i])
    print(round(sens[i],2))

votes_sat
0.9
votes_qual
0.98
votes_bro
0.99
votes_pack
1.0
votes_naa
0.99
votes_before
0.79
votes_delay
0.89
votes_part
0.92
votes_wrong
0.99
votes_od
0.98
votes_ss
0.98
votes_etc
0.96
votes_ret
0.98


### - satisfied만 not 빼보기

In [243]:
votes = [0 for i in range(len(df['review_comment_message']))]
dictionary = ['' for i in range(len(df['review_comment_message']))]

for term in dict_df['sat'].dropna():
    g= re.compile(r"(\b%s\b)"%term)
    for row, test in enumerate(df['review_comment_message']):
        
        m = g.search(str(test).lower())
        if m:
            votes[row] += 1
            if len(dictionary[row]) <= 1:
                dictionary[row] += term
            else:
                dictionary[row] += ',' + term


In [258]:
new_sat = []
for i in dict_df['sat']:
    new_sat.append('[^(not)]'+i)
    
new_sat2 = []
for i in dict_df['sat']:
    new_sat2.append('^'+i)

In [259]:
votes2 = [0 for i in range(len(df['review_comment_message']))]
dictionary2 = ['' for i in range(len(df['review_comment_message']))]

for term in new_sat:
    g= re.compile(r"(\b%s\b)"%term)
    for row, test in enumerate(df['review_comment_message']):
        m = g.search(str(test).lower())
        if m:
            votes2[row] += 1
            if len(dictionary2[row]) <= 1:
                dictionary2[row] += term
            else:
                dictionary2[row] += ',' + term

In [250]:
new_sat2 = []
for i in dict_df['sat']:
    new_sat2.append('^'+i)
    

In [252]:
votes3 = [0 for i in range(len(df['review_comment_message']))]
dictionary3 = ['' for i in range(len(df['review_comment_message']))]

for ind,term in enumerate(new_sat):
    g= re.compile(r"(\b%s\b)"%term)
    gg = re.compile(r"(%s\b)"%new_sat2[ind])
    
    for row, test in enumerate(df['review_comment_message']):
        m = g.search(str(test).lower())
        mm = gg.search(str(test).lower())
        if m or mm:
            votes3[row] += 1
            if len(dictionary3[row]) <= 1:
                dictionary3[row] += term
            else:
                dictionary3[row] += ',' + term

In [249]:
len(votes)

3584

In [245]:
sum(votes2)

4810

In [420]:
cnt1 =0
cnt2 =0
cnt3 = 0
for i in range(len(votes)):
    if votes[i] != 0:
        cnt1 += 1
    if votes2[i] != 0:
        cnt2 += 1 
    if votes3[i] != 0:
        cnt3 += 1 
print(cnt1, cnt2, cnt3)

13 6 6


## 완전 원본에 테스트해보기

In [53]:
dict_df = pd.read_excel('total_dict_apo_2202.xlsx')

In [88]:
test = pd.read_csv('final_dataset_var2.csv')

### - 원본 &#39; 전처리

In [94]:

comments = test['review_comment_message_english'].tolist()
new = []
for i in comments:
    
    if pd.notnull(i):
        apo = "&#39;"
        g = re.compile(r"(%s)"% apo)
        m = g.search(i)
        if m:
            new.append(i.replace('&#39;', "\'"))
        else:
            new.append(i)
    else: 
        new.append('')
        
test['review_comment_message_english'] = new



In [103]:
# test.to_csv('final_dataset_var2_apo.csv', index_label= False, index=False)

In [9]:
testco = test[pd.notnull(test['review_comment_message_english'])]['review_comment_message_english']

In [10]:
len(testco)

38892

In [11]:
votes=[]
for columns in range(len(dict_df.columns)):
    votes.append([0 for i in range(len(testco))])

In [12]:
dictionary=[]
for columns in range(len(dict_df.columns)):
    dictionary.append(['' for i in range(len(testco))])

In [13]:
len(votes[0])

38892

In [14]:
cnt =0

for ind,col in dict_df.iteritems():
    for term in col.dropna():
        for row,test in enumerate(testco):
            g = re.compile(r"(\b%s\b)"%term)
            m = g.search(test.lower())
            
            if m:
                votes[cnt][row] += 1
                if len(dictionary[cnt][row]) <= 1:
                    dictionary[cnt][row] += term
                else:
                    dictionary[cnt][row] += ',' + term    
    cnt += 1
    print(cnt)

testco = pd.DataFrame(testco)

1
2
3
4
5
6
7
8
9
10
11
12
13


In [15]:
for columns in range(len(dict_df.columns)):
    testco['votes_%s'%dict_df.columns[columns]] = votes[columns]  
    testco['votes_%s_dictionary'%dict_df.columns[columns]] = dictionary[columns] 

In [16]:
testco

review_comment_message_english  votes_sat  \
1                          very good hair stays straight          2   
2                                               liked it          1   
4             the product was delivered on time and well          1   
5                                    I am very satisfied          2   
9                        within the excellent time frame          1   
11                          great better than i expected          2   
21     I asked for cancellation of the purchase becau...          0   
22     I like the product but he gets married a lot o...          1   
23     I bought 2 products a botox is a moisturizing ...          3   
24     product arrived in perfect condition and befor...          6   
35     the product arrived well before the term I lov...          4   
36            the product came right before the deadline          3   
41            recommend arrived well before the deadline          2   
42              excellent product and very fast delivery          2   
43     came well before the deadline and exactly as i...          3   
56                                         fast delivery          0   
57     the quality is great and arrived well before t...          3   
59                                             wonderful          1   
61                  the order arrived in a timely manner          0   
62     bad store does not deliver the product or resp...          0   
63                              well I loved the product          5   
64     very satisfied delivery super fast show congra...          3   
66     good for who is beginning to cut bad hair to t...          1   
68     original product and fast shipping recommend t...          2   
71     the product I received the product and I was s...          0   
76                  no product location delayed delivery          0   
78                                           reliability          0   
79     is the second time I buy at baratheone the fir...          0   
82     I am dissatisfied with the delay in delivering...          0   
84          I like to buy there in the stark I recommend          3   
...                                                  ...        ...   
92928               very good movie arrived as announced          2   
92931                                                 ok          1   
92939                         I like to buy by targaryen          1   
92940                        the product arrived on time          0   
92941                                           liked it          1   
92942                                    fully satisfied          2   
92943                               recommend this store          3   
92945                 very good product care as expected          4   
92947        I&#39;m a customer of the lannister stores.          0   
92948  the product delivered does not match the purch...          0   
92950  product within the conforming purchase and del...          2   
92953                       fast and efficient recommend          2   
92955  I bought a lot of time, I never had a problem ...          1   
92957                                    within expected          0   
92959  much lower quality than gives photo disappoint...          0   
92963  the product delivered is very different from t...          0   
92964  smaller than imagined the photo shows that big...          1   
92966  again came missing the item artificial flower ...          0   
92967  I liked the store because it has varieties so ...          5   
92970                        A piece of junk got nothing          0   
92971  much delay in delivery did not meet the date i...          0   
92972                  excellent quality product can buy          4   
92973                              everything as planned          0   
92975  that legal I received the product well before ...          2   
92977  only the freights of targaryen is one of th

In [18]:
testco.to_excel('original_test_results_dict_temp1_2202.xlsx')

In [493]:
testco2 = testco['review_comment_message_english']

In [519]:
string = testco2[-1:].values

In [520]:
string

array(['good afternoon product sent wrong I will have to move to the post office because I live in a condominium I had to receive and I will still wait to arrive until after I receive the correct product I paid via ticket'],
      dtype=object)

In [525]:
type(string[0])

str

In [526]:
for term in stdict:
    g = re.compile(r"(\b%s\b)"%term)
    m = g.search(string[0].lower()) 
    if m:
        
        print(term)


correct
correct product
good
